#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor HDMI-A-0 -d I II III IV V VI VII VIII IX X

bspc config border_width 3
bspc config window_gap 1
bspc config top_padding 25
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config border_radius 10
bspc config bottom_padding 0
bspc config top_monocle_padding 10
bspc config left_monocle_padding 0
bspc config bottom_monocle_padding 0
bspc config right_monocle_padding 0

#colors
bspc config normal_border_color "#2c5161"
bspc config active_border_color "#2e86ab"
bspc config focused_border_color "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color "#dd2727"

#widnows opening on a certain workspace
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^3'
bspc rule -a Spotify desktop='^10'
bspc rule -a Emacs state=tiled

#start
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/bin/emacs --daemon &
feh --bg-fill ~/Pictures/InvokerE.jpg
picom -b
ibus-daemon -drxR
flameshot &
udiskie &
#xfce4-power-manager &
#Resolution
#xrandr --newmode "1920x1080_60.00" 173.00 1920 2048 2248 2576 1080 1083 1088 1120 -hsync +vsync &
#xrandr --addmode HDMI-A-0 "1920x1080_60.00" &
#xrandr --output HDMI-A-0 --mode 1920x1080_60.00 &

#Lock and suspend
#$HOME/.local/bin/locker &
